version: '3'
volumes:
    node_modules:
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - node_modules:/usr/src/node_modules
      - .:/usr/src
    environment:
      - NODE_ENV=development
    command: npm run develop